# Generated by Django 3.2.25 on 2024-07-08 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('image_principal', models.FileField(upload_to='static/images/boutique/produits/')),
                ('prix', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('quantite', models.IntegerField()),
                ('image_un', models.FileField(upload_to='static/images/boutique/produits/')),
                ('image_deux', models.FileField(upload_to='static/images/boutique/produits/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.categorie')),
            ],
        ),
    ]
